// ============================================
// QuizCraft Pro — WebSocket Event Constants
// ============================================

export const WS = {
  // ─── Client → Server ──────────────────────────
  // Waiting room
  JOIN_WAITING_ROOM: 'JOIN_WAITING_ROOM',
  // Quiz session
  JOIN_QUIZ: 'JOIN_QUIZ',
  ANSWER_QUESTION: 'ANSWER_QUESTION',
  FLAG_QUESTION: 'FLAG_QUESTION',
  NAVIGATE_QUESTION: 'NAVIGATE_QUESTION',
  SUBMIT_QUIZ: 'SUBMIT_QUIZ',
  // Proctoring
  PROCTOR_WARNING: 'PROCTOR_WARNING',
  // Admin
  ADMIN_JOIN_CONTEST_ROOM: 'ADMIN_JOIN_CONTEST_ROOM',
  ADMIN_BROADCAST: 'ADMIN_BROADCAST',
  FORCE_SUBMIT_PARTICIPANT: 'FORCE_SUBMIT_PARTICIPANT',
  // Keep-alive
  PING: 'PING',

  // ─── Server → Client ──────────────────────────
  WAITING_ROOM_COUNT: 'WAITING_ROOM_COUNT',
  CONTEST_STARTED: 'CONTEST_STARTED',
  CONTEST_DELAYED: 'CONTEST_DELAYED',
  SESSION_NEW: 'SESSION_NEW',
  SESSION_RESTORED: 'SESSION_RESTORED',
  SESSION_CLOSED: 'SESSION_CLOSED',
  ANSWER_SAVED: 'ANSWER_SAVED',
  TIMER_SYNC: 'TIMER_SYNC',
  AUTO_SUBMIT_WARNING: 'AUTO_SUBMIT_WARNING',
  QUIZ_SUBMITTED: 'QUIZ_SUBMITTED',
  PROCTOR_WARNING_ACK: 'PROCTOR_WARNING_ACK',
  BULK_UPDATE: 'BULK_UPDATE',
  PARTICIPANT_JOINED: 'PARTICIPANT_JOINED',
  PARTICIPANT_SUBMITTED: 'PARTICIPANT_SUBMITTED',
  PARTICIPANT_DISCONNECTED: 'PARTICIPANT_DISCONNECTED',
  PROCTOR_ALERT: 'PROCTOR_ALERT',
  PONG: 'PONG',
} as const;

export type WSEvent = (typeof WS)[keyof typeof WS];
