# STORAGE MODULE

variable "frontend_origin" {
  type        = string
  description = <<-EOT
    Frontend origin allowed to talk to this bucket directly from the browser
    (e.g. "https://ysmquizbuzz.com"). Needed because the ambassador-proof,
    ambassador-profile, ambassador-campaign-poster, and proctoring-snapshot
    upload flows all PUT straight from the browser to a presigned S3 URL
    (see backend/src/providers/s3.provider.ts) — with no CORS rule on the
    bucket, every one of those browser-direct PUTs fails with a generic
    "Failed to fetch" (a blocked CORS preflight), which is indistinguishable
    from a permissions error in the browser's network tab. Should match
    CORS_ALLOWED_ORIGINS in the backend's own env (see admin_instance's and
    live_contest's userdata.sh.tpl — both set it to "https://$${var.domain_name}").
  EOT
}

resource "aws_s3_bucket" "main" {
  bucket = "quizbuzz-assets-prod"
  force_destroy = false
  tags = { Name = "quizbuzz-assets", Purpose = "certificates-and-assets" }

  lifecycle {
    prevent_destroy = true
  }
}

# Versioning
resource "aws_s3_bucket_versioning" "main" {
  bucket = aws_s3_bucket.main.id
  versioning_configuration {
    status = "Enabled"
  }
}

# Encryption
resource "aws_s3_bucket_server_side_encryption_configuration" "main" {
  bucket = aws_s3_bucket.main.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Public-access block
#
# ACL-based public access stays fully blocked — nothing in this app should
# ever be made public by object/bucket ACLs. block_public_policy and
# restrict_public_buckets are relaxed so the SCOPED bucket policy below can
# take effect for exactly two prefixes; every other prefix (certificates/,
# proctoring/, ambassador-proof/) has no policy grant here and stays fully
# private, served only through presigned URLs the app generates on demand.
#
# WHY THIS CHANGED FROM "all four flags true": that fully-locked version is
# what kept getting silently un-done by hand in the AWS Console (flipping
# these to false) because two upload flows in the backend — contest banner
# images (contest.controller.ts uploadBanner) and ambassador campaign
# poster images (ambassador-campaign.service.ts getPosterUploadUrl, whose
# own comment says the frontend "strips the query string off [the presigned
# PUT URL] to get the permanent object URL to save") — were both built
# assuming their uploaded objects would be plainly, permanently public.
# Every `terraform apply` reverted that console change, breaking banner/
# poster rendering again. The real fix is scoping public read to just
# those two prefixes in code (see aws_s3_bucket_policy.public_marketing_assets
# below) instead of opening the whole bucket by hand.
resource "aws_s3_bucket_public_access_block" "main" {
  bucket = aws_s3_bucket.main.id

  block_public_acls       = true
  block_public_policy     = false
  ignore_public_acls      = true
  restrict_public_buckets = false
}

# Public read access, scoped ONLY to prefixes that are genuinely meant to be
# public marketing/branding assets:
#   - banners/                          contest banner images (public contest
#                                        listing/registration pages)
#   - ambassador-campaign-poster/       campaign poster images (WhatsApp/social
#                                        link-preview crawlers can't use presigned
#                                        URLs — they need a permanent plain URL)
#   - ambassador-campaign-reward-image/ milestone/speed-bonus/leaderboard
#                                        "goodie" images shown on public
#                                        campaign and ambassador dashboard pages
#   - ambassador-campaign-kit-asset/    ambassador kit attachments (PDFs,
#                                        graphics) — downloaded via a plain
#                                        <a href download>, not a fetch call,
#                                        so it also needs a bare public URL
#   - contest-prize-reward-image/       contest prize goodie images shown on
#                                        public contest pages
#   - logos/                            org logos (certificates, org-branded
#                                        public pages)
#   - app-settings/logo/                platform app logo (login/public pages)
# All of these are uploaded via a presigned PUT (or the base64 upload path,
# for logos/app-settings) and then referenced by their bare, permanent object
# URL — same reasoning as banners/ambassador-campaign-poster above, so they
# need the same public-read grant or the browser gets AccessDenied on the
# <img> tag even though the upload itself succeeded.
# Certificates, proctoring snapshots, and ambassador ID/proof/profile
# documents are NOT in this policy — they stay private and are served
# exclusively via time-limited presigned GET URLs generated by the backend
# at request time.
resource "aws_s3_bucket_policy" "public_marketing_assets" {
  bucket = aws_s3_bucket.main.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "PublicReadMarketingAssets"
        Effect    = "Allow"
        Principal = "*"
        Action    = "s3:GetObject"
        Resource = [
          "${aws_s3_bucket.main.arn}/banners/*",
          "${aws_s3_bucket.main.arn}/ambassador-campaign-poster/*",
          "${aws_s3_bucket.main.arn}/ambassador-campaign-reward-image/*",
          "${aws_s3_bucket.main.arn}/ambassador-campaign-kit-asset/*",
          "${aws_s3_bucket.main.arn}/contest-prize-reward-image/*",
          "${aws_s3_bucket.main.arn}/logos/*",
          "${aws_s3_bucket.main.arn}/app-settings/logo/*",
        ]
      }
    ]
  })

  # Must apply after the public access block is relaxed above — AWS
  # rejects a public-granting bucket policy while block_public_policy is
  # still true, so this ordering has to be explicit rather than inferred.
  depends_on = [aws_s3_bucket_public_access_block.main]
}

# CORS — required for every browser-direct presigned PUT this app does
# (ambassador ID/proof, ambassador profile photo, campaign poster, proctoring
# snapshots — see s3.provider.ts's getPresignedPutUrl, called from
# ambassador.service.ts, ambassador-campaign.service.ts, and
# quiz-proctoring.controller.ts). Without this resource the bucket has never
# had a CORS rule, so every one of those browser fetch()/PUT calls fails
# with "Failed to fetch" before it ever reaches an IAM/policy check.
resource "aws_s3_bucket_cors_configuration" "main" {
  bucket = aws_s3_bucket.main.id

  cors_rule {
    allowed_methods = ["PUT", "GET"]
    allowed_origins = [var.frontend_origin]
    allowed_headers = ["*"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}

# Lifecycle
resource "aws_s3_bucket_lifecycle_configuration" "main" {
  bucket = aws_s3_bucket.main.id

  rule {
    id     = "expire-old-certificates"
    status = "Enabled"

    filter {
      prefix = "certificates/"
    }

    # Delete the current version after 365 days
    expiration {
      days = 365
    }

    # Delete old non-current versions after 30 days
    # (these are created by versioning when a file is re-uploaded)
    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }
}

output "bucket_name" {
  value       = aws_s3_bucket.main.id
  description = "S3 bucket name — needed for S3_BUCKET env var in your containers"
}

output "bucket_arn" {
  value       = aws_s3_bucket.main.arn
  description = "S3 bucket ARN — needed for the EC2 IAM policy to allow S3 access"
}
